"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import timingapp
from timingapp.model.api_v1_time_entries_start_post201_response import ApiV1TimeEntriesStartPost201Response


class TestApiV1TimeEntriesStartPost201Response(unittest.TestCase):
    """ApiV1TimeEntriesStartPost201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1TimeEntriesStartPost201Response(self):
        """Test ApiV1TimeEntriesStartPost201Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1TimeEntriesStartPost201Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
