"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import timingapp
from timingapp.model.color import Color
from timingapp.model.project import Project
globals()['Color'] = Color
globals()['Project'] = Project
from timingapp.model.api_v1_projects_get_request import ApiV1ProjectsGetRequest


class TestApiV1ProjectsGetRequest(unittest.TestCase):
    """ApiV1ProjectsGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1ProjectsGetRequest(self):
        """Test ApiV1ProjectsGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1ProjectsGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
