"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import timingapp
from timingapp.api.projects_api import ProjectsApi  # noqa: E501


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_projects_get(self):
        """Test case for api_v1_projects_get

        Return a list containing all projects.  # noqa: E501
        """
        pass

    def test_api_v1_projects_hierarchy_get(self):
        """Test case for api_v1_projects_hierarchy_get

        Return the complete project hierarchy.  # noqa: E501
        """
        pass

    def test_api_v1_projects_post(self):
        """Test case for api_v1_projects_post

        Create a new project.  # noqa: E501
        """
        pass

    def test_api_v1_projects_project_id_delete(self):
        """Test case for api_v1_projects_project_id_delete

        Delete the specified project and all of its children.  # noqa: E501
        """
        pass

    def test_api_v1_projects_project_id_get(self):
        """Test case for api_v1_projects_project_id_get

        Display the specified project.  # noqa: E501
        """
        pass

    def test_api_v1_projects_project_id_put(self):
        """Test case for api_v1_projects_project_id_put

        Update the specified project.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
