"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import timingapp
from timingapp.model.color import Color
globals()['Color'] = Color
from timingapp.model.api_v1_projects_project_id_delete_request import ApiV1ProjectsProjectIdDeleteRequest


class TestApiV1ProjectsProjectIdDeleteRequest(unittest.TestCase):
    """ApiV1ProjectsProjectIdDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1ProjectsProjectIdDeleteRequest(self):
        """Test ApiV1ProjectsProjectIdDeleteRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1ProjectsProjectIdDeleteRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
