"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import timingapp
from timingapp.api.time_entries_api import TimeEntriesApi  # noqa: E501


class TestTimeEntriesApi(unittest.TestCase):
    """TimeEntriesApi unit test stubs"""

    def setUp(self):
        self.api = TimeEntriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_time_entries_activity_id_delete(self):
        """Test case for api_v1_time_entries_activity_id_delete

        Delete the specified time entry.  # noqa: E501
        """
        pass

    def test_api_v1_time_entries_activity_id_get(self):
        """Test case for api_v1_time_entries_activity_id_get

        Display the specified time entry.  # noqa: E501
        """
        pass

    def test_api_v1_time_entries_activity_id_put(self):
        """Test case for api_v1_time_entries_activity_id_put

        Update the specified time entry.  # noqa: E501
        """
        pass

    def test_api_v1_time_entries_get(self):
        """Test case for api_v1_time_entries_get

        Return a list of time entries.  # noqa: E501
        """
        pass

    def test_api_v1_time_entries_post(self):
        """Test case for api_v1_time_entries_post

        Create a new time entry.  # noqa: E501
        """
        pass

    def test_api_v1_time_entries_start_post(self):
        """Test case for api_v1_time_entries_start_post

        Start a new timer.  # noqa: E501
        """
        pass

    def test_api_v1_time_entries_stop_put(self):
        """Test case for api_v1_time_entries_stop_put

        Stop the currently running timer.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
