"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import timingapp
from timingapp.model.api_v1_teams_team_id_members_get200_response import ApiV1TeamsTeamIdMembersGet200Response


class TestApiV1TeamsTeamIdMembersGet200Response(unittest.TestCase):
    """ApiV1TeamsTeamIdMembersGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1TeamsTeamIdMembersGet200Response(self):
        """Test ApiV1TeamsTeamIdMembersGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1TeamsTeamIdMembersGet200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
