"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import timingapp
from timingapp.api.reports_api import ReportsApi  # noqa: E501


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self):
        self.api = ReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_report_get(self):
        """Test case for api_v1_report_get

        Generate a report that can contain both time entries and app usage.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
