"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import timingapp
from timingapp.model.project import Project
globals()['Project'] = Project
from timingapp.model.api_v1_time_entries_get_request import ApiV1TimeEntriesGetRequest


class TestApiV1TimeEntriesGetRequest(unittest.TestCase):
    """ApiV1TimeEntriesGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1TimeEntriesGetRequest(self):
        """Test ApiV1TimeEntriesGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1TimeEntriesGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
