"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import timingapp
from timingapp.model.api_v1_projects_hierarchy_get200_response import ApiV1ProjectsHierarchyGet200Response


class TestApiV1ProjectsHierarchyGet200Response(unittest.TestCase):
    """ApiV1ProjectsHierarchyGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1ProjectsHierarchyGet200Response(self):
        """Test ApiV1ProjectsHierarchyGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1ProjectsHierarchyGet200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
