"""
    API Reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import timingapp
from timingapp.model.api_v1_time_entries_get201_response import ApiV1TimeEntriesGet201Response


class TestApiV1TimeEntriesGet201Response(unittest.TestCase):
    """ApiV1TimeEntriesGet201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV1TimeEntriesGet201Response(self):
        """Test ApiV1TimeEntriesGet201Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV1TimeEntriesGet201Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
